columnSuffix: null
contentColumnType: text
fieldGroup: 12aa936c-807f-4ec3-81dc-69283a344171 # Profile
handle: profileOptimizedImages
instructions: null
name: 'Profile Optimized Images'
searchable: true
settings:
  displayDominantColorPalette: true
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  variants:
    -
      __assoc__:
        -
          - width
          - '100'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - jpg
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
