fieldLayouts:
  93ce2e82-1407-4642-9ca7-b1fea1df0a56:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 68e87e98-2f33-4af9-8393-13b87ce70be8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c05161c0-a294-4d47-8909-1cfc88c2f970 # Profile Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bc3c007-0c10-49ee-bb96-b2b315562625
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 380e3b7e-07de-4d39-b0e5-360f5e87d00d # Profile Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa997dbd-8bd2-417a-9f19-fb2df83c282f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9687721c-33b8-4a40-abb7-5c42e07ce274 # Profile Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b0595a3-65a0-4fd5-84fe-29b540c49677
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31b8c511-37f9-4d83-956d-5aa215572122 # Profile URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0bd2993-d694-44f1-837a-e520d9075c63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d6df6fe7-14f3-42a3-9949-dcee7c8c26d9 # Profile GitHub URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84d2e1bd-7e21-4161-82aa-b298d9882ac0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 406c20cb-9b86-4b0d-9123-1ce57220e2a8 # Profile Twitter URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fd497b0-1368-4567-81d5-9acc1d502169
            userCondition: null
            warning: null
            width: 100
        name: Profile
        uid: f7b7a54d-627d-4038-916d-3306ae9a99b6
        userCondition: null
handle: guests
hasTitleField: true
name: Guests
section: 214e4dc6-a454-4df0-a1f5-cd94ecdab53f # Guests
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
