dateModified: 1695404869
email:
  fromEmail: andrew@nystudio107.com
  fromName: devMode
  transportType: craft\mail\transportadapters\Sendmail
fs:
  devmodeEpisodes:
    hasUrls: true
    name: 'Devmode Episodes'
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET
      bucketSelectionMode: manual
      cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
      cfPrefix: $CLOUDFRONT_PATH_PREFIX
      expires: '3 months'
      keyId: $S3_KEY_ID
      makeUploadsPublic: false
      region: $S3_REGION
      secret: $S3_SECRET
      storageClass: ''
      subfolder: episodes
    type: craft\awss3\Fs
    url: $CLOUDFRONT_URL
  devmodeSite:
    hasUrls: true
    name: 'Devmode Site'
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET
      bucketSelectionMode: manual
      cfDistributionId: CLOUDFRONT_DISTRIBUTION_ID
      cfPrefix: $CLOUDFRONT_PATH_PREFIX
      expires: '3 months'
      keyId: $S3_KEY_ID
      makeUploadsPublic: false
      region: $S3_REGION
      secret: $S3_SECRET
      storageClass: ''
      subfolder: site
    type: craft\awss3\Fs
    url: $CLOUDFRONT_URL
  devmodeTranscripts:
    hasUrls: true
    name: 'Devmode Transcripts'
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET
      bucketSelectionMode: manual
      cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
      cfPrefix: $CLOUDFRONT_PATH_PREFIX
      expires: '3 months'
      keyId: $S3_KEY_ID
      makeUploadsPublic: false
      region: $S3_REGION
      secret: $S3_SECRET
      storageClass: ''
      subfolder: transcripts
    type: craft\awss3\Fs
    url: $CLOUDFRONT_URL
  devmodeUsers:
    hasUrls: true
    name: 'Devmode Users'
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET
      bucketSelectionMode: manual
      cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
      cfPrefix: $CLOUDFRONT_PATH_PREFIX
      expires: '3 months'
      keyId: $S3_KEY_ID
      makeUploadsPublic: false
      region: $S3_REGION
      secret: $S3_SECRET
      storageClass: ''
      subfolder: users
    type: craft\awss3\Fs
    url: $CLOUDFRONT_URL
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0c790066-43c5-4b67-b6d9-8492fa40cf71: Show # Show
    1a66bf43-6fcc-4a78-bf36-0f350b930430: 'Episodes Index' # Episodes Index
    1be1c156-82fa-4f08-bb63-6d3417da2844: 'Optimized Images' # Optimized Images
    2a4761bd-2461-4db9-96a0-4f52b8cef633: devMode # devMode
    2bb6f342-1735-446e-b9fe-754f94dac82f: Answer # Answer
    4d90d0e7-b705-4035-b396-2f82ce5bb871: 'Error Image' # Error Image
    5f70b9e0-f42b-4fdb-bcf6-5e82691d89de: 'Site Offline' # Site Offline
    6def66f0-2a8f-4b88-9435-7f9cc1ccfe9c: 'Show Genre' # Show Genre
    7e338b73-ac10-44cf-892e-04afc0164991: 'Episode Guests' # Episode Guests
    07f04bdf-277d-4010-9fbe-497cd9593324: 'Related Episodes' # Related Episodes
    7f6ad724-41b7-4a93-bef9-7de87d1bb23e: Calendar # Calendar
    8c9dd611-b43b-4e22-b076-3f6a6362c93e: 'Episode Reference Links' # Episode Reference Links
    9aae2c4b-7316-4ee9-a2d1-41474766b361: Homepage # Homepage
    12aa936c-807f-4ec3-81dc-69283a344171: Profile # Profile
    18d7721b-780b-4a44-976a-716c3df0bb7a: 'Error Headline' # Error Headline
    19dfdfbb-837c-46d5-87bf-e6540df98dc4: Hosts # Hosts
    19e4e8ba-93c2-4a86-8c57-9b54d46e0981: Site # Site
    29da80bf-c705-441b-be33-96df307c84c6: '503 Service Unavailable' # 503 Service Unavailable
    31b8c511-37f9-4d83-956d-5aa215572122: 'Profile URL' # Profile URL
    032dc0eb-27cf-4034-ad36-dc8c274a455e: Guests # Guests
    41fdb4c8-4774-4101-918f-1412190b085b: 'Profile Optimized Images' # Profile Optimized Images
    52b673e7-3d80-44a4-94f7-43eaafcc9d6f: '404 Not Found' # 404 Not Found
    78ad1f1e-5dc5-4cff-b19f-43aa4ec02869: '404 Not Found' # 404 Not Found
    087ee23d-4f8f-42d4-af12-99fcc2462247: 'Show Info' # Show Info
    88db3e41-57f4-404d-b3ea-762b09c37afe: Errors # Errors
    0090f7a3-1e22-4fb5-9ae0-01de38805601: 'Episode Media' # Episode Media
    98dbc824-8c89-4138-9b0f-011a96875a7a: Links # Links
    98f56e95-4be6-4238-a110-1f21574fa642: 'Devmode Users' # Devmode Users
    214e4dc6-a454-4df0-a1f5-cd94ecdab53f: Guests # Guests
    324e7a11-3346-41e7-a29d-4636ab907e51: 'Episode Number' # Episode Number
    380e3b7e-07de-4d39-b0e5-360f5e87d00d: 'Profile Title' # Profile Title
    406c20cb-9b86-4b0d-9123-1ce57220e2a8: 'Profile Twitter URL' # Profile Twitter URL
    428ec106-b2d1-4d48-a5fa-de192155dff5: 'Show URL' # Show URL
    486a0853-47b2-4509-97ad-43fe3ec42074: About # About
    913ea665-c268-4177-8054-fe76f80101c6: Episodes # Episodes
    2405ed1c-fd52-4264-a96a-f6e6fab437b5: 'Show Sub-Title' # Show Sub-Title
    7540db37-7ec3-4471-9de6-36bde06e949a: 'Devmode Site' # Devmode Site
    9436ac5e-44de-4fe9-be59-fd1f0fc26941: Owners # Owners
    34348a98-83b9-4f2d-8e14-0437ec964a15: devMode # devMode
    49649e9a-033b-4ddf-9f3d-26a480502993: About # About
    61953a92-8b34-4678-9bae-fd5a45142f26: 'Episode Tags' # Episode Tags
    519413e8-a432-4cfe-98c5-5f81e9519f2a: 'Generic Error' # Generic Error
    523395ea-5738-4ca5-a119-f32221ea5ca8: 'Episode Transcript' # Episode Transcript
    8011817c-9518-4a31-9aa8-cad6d4a08b81: 'Episode Summary' # Episode Summary
    9089688f-6602-4d69-91cd-ec9a94c4bc6f: '503 Service Unavailable' # 503 Service Unavailable
    9687721c-33b8-4a40-abb7-5c42e07ce274: 'Profile Bio' # Profile Bio
    14605669-4768-4f57-88d6-1f06480a9b80: 'Show iTunes URL' # Show iTunes URL
    50012289-791c-48b2-8df1-31a8f5eb5380: 'Episodes Index' # Episodes Index
    86909527-3ec4-4d57-a44c-167649eb86bf: 'Show Description' # Show Description
    a009e969-e0ed-429e-9ab3-98561af05518: FAQs # FAQs
    a1eaefb7-b32a-436d-a218-3fc7be02c917: Calendar # Calendar
    a4be3483-f316-4f96-8820-3914ad7b863a: 'Site Offline' # Site Offline
    a5cf9c0d-1797-4a60-8c47-bc28c5f01a95: 'Episode Hosts' # Episode Hosts
    a8f2ec1a-a218-451c-a658-e3c600ddb5fa: 'Show Title' # Show Title
    a9d3a609-1f18-4cb7-afc3-3c103a7e09de: Homepage # Homepage
    ab0ca0e9-1308-472f-92a5-2ab0cbd84943: 'Show RSS Feed URL' # Show RSS Feed URL
    b5eb01ec-a6ed-4a08-9438-64e7138b08f0: FAQs # FAQs
    bd8ef0d7-f73b-4138-ac52-c14d11dd780e: 'Devmode Transcripts' # Devmode Transcripts
    bda219fa-bace-4d8b-ad3a-08243caaf6ca: 'Show Image' # Show Image
    bfbd2913-36d8-4e54-9f9c-644e793f0ae9: Episodes # Episodes
    c05161c0-a294-4d47-8909-1cfc88c2f970: 'Profile Company' # Profile Company
    c1f6af30-7375-4feb-92ef-a3ed16ba69b2: Episodes # Episodes
    ca279869-925f-4960-865c-96cacd2aa942: 'Show Email' # Show Email
    cc4ea2bd-3bde-4bad-8f72-272fcc3c2a19: About # About
    d6df6fe7-14f3-42a3-9949-dcee7c8c26d9: 'Profile GitHub URL' # Profile GitHub URL
    e0264ea5-7834-42de-9f8f-c611149453d0: Question # Question
    e69c8edb-d562-4367-9a05-91a6fd2c7d99: 'Devmode Episodes' # Devmode Episodes
    e81379aa-e0c7-45c0-b506-c4ab8fce6bce: 'Generic Error' # Generic Error
    e1087165-5769-428d-bf14-c98e6011cf5e: 'Error Text' # Error Text
    eecc24bf-e253-43b8-b327-632e0dc07fa6: 'Show Technologies Links' # Show Technologies Links
    fc24a736-c435-4d8a-aeb3-6105afce1d91: Episodes # Episodes
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  disqus:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      customLogin: false
      disqusPublicKey: $DISQUS_PUBLIC_KEY
      disqusSecretKey: $DISQUS_SECRET_KEY
      disqusShortname: devmode-fm
      loginButton: ''
      loginHeight: 400
      loginIcon: ''
      loginLogoutUrl: ''
      loginName: ''
      loginUrl: ''
      loginWidth: 800
      useSSO: false
  fastcgi-cache-bust:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings:
      cachePath: /var/run/nginx-cache/devmode
  icalendar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    enabled: true
    licenseKey: $PLUGIN_IMAGEOPTIMIZE_LICENSE
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: true
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - $SERVERLESS_SHARP_CLOUDFRONT_URL
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
                -
                  - includeBucketPrefix
                  - ''
      lowerQualityRetinaImageVariants: false
      transformClass: nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
  minify:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retour:
    enabled: true
    licenseKey: $PLUGIN_RETOUR_LICENSE
    schemaVersion: 3.0.12
    settings: null
  seomatic:
    enabled: true
    licenseKey: $PLUGIN_SEOMATIC_LICENSE
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: 'âš™ '
      devModeCpTitlePrefix: 'ðŸš§âš™ '
      devModeTitlePrefix: '[devMode] '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      environment: live
      generatorEnabled: true
      headersEnabled: true
      maxDescriptionLength: 300
      maxTitleLength: 120
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: //
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      sitemapsEnabled: true
  transcoder:
    enabled: true
    licenseKey: $PLUGIN_TRANSCODER_LICENSE
    schemaVersion: 1.0.0
    settings: null
  typogrify:
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  webperf:
    enabled: true
    licenseKey: $PLUGIN_WEBPERF_LICENSE
    schemaVersion: 1.0.1
    settings:
      automaticallyTrimDataSamples: true
      automaticallyTrimErrorSamples: true
      connectThreshold: 0.5
      craftDbMsThreshold: 2
      craftOtherMsThreshold: 2
      craftTotalMsThreshold: 2
      craftTwigMsThreshold: 2
      dashboardAverageColor: '#ffff00'
      dashboardFastColor: '#00c800'
      dashboardSlowColor: '#c80000'
      dataSamplesStoredLimit: 100000
      displaySidebar: true
      dnsThreshold: 0.5
      domInteractiveThreshold: 5
      errorSamplesStoredLimit: 1000
      excludePatterns:
        -
          pattern: '/webperf/.*'
        -
          pattern: '/cpresources/.*'
        -
          pattern: /rss
      filterBotUserAgents: true
      firstByteThreshold: 2
      firstContentfulPaintThreshold: 5
      firstPaintThreshold: 5
      includeBeacon: true
      includeCraftProfiling: true
      includeCraftWarnings: false
      pageLoadThreshold: 10
      pluginName: Webperf
      rateLimitMs: 500
      staticCachedSite: false
      trimOutlierDataSamples: true
      webpageTestApiKey: ''
system:
  edition: pro
  live: true
  name: devMode.fm
  retryDuration: 60
  schemaVersion: 4.5.3.0
  timeZone: America/New_York
